# Generated by Django 4.2.2 on 2023-06-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='accept',
            field=models.BooleanField(default=None),
        ),
        migrations.AlterField(
            model_name='announce',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
