# Generated by Django 4.2.2 on 2023-06-23 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0002_reply_accept_alter_announce_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
