# Generated by Django 4.2.2 on 2023-06-27 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announces', '0007_alter_announce_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announce',
            name='file',
        ),
        migrations.RemoveField(
            model_name='announce',
            name='image',
        ),
    ]
